import "./globals.css";
import type { Metadata } from "next";
import RootPage from "./rootPage";
import Providers from "./Providers";

export const metadata: Metadata = {
  title: "Book Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
