import NavigationBar from "@/components/NavigationBar";
import "./globals.css";
import type { Metadata } from "next";
import Footer from "@/components/Footer";
import CartNotification from "@/components/CartNotification";
import Overlay from "@/components/Overlay";
import CartMini from "@/components/CartMini";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavigationBar />
        {/* <CartNotification /> */}
        {/* <CartMini /> */}
        {/* <Overlay /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
